#ifndef BRADYPOS_L4_SYSCALLS_H
#define BRADYPOS_L4_SYSCALLS_H

enum L4_syscall_nr
{
    SYS_SPACE_CONTROL,
    SYS_THREAD_CONTROL,
    SYS_PROCESSOR_CONTROL,
    SYS_MEMORY_CONTROL,
    SYS_IPC,
    SYS_LIPC,
    SYS_UNMAP,
    SYS_EXCHANGE_REGISTERS,
    SYS_SYSTEM_CLOCK,
    SYS_THREAD_SWITCH,
    SYS_SCHEDULE,
};

#endif
