name: Build bsh tests

on:
  push:
    paths:
      - .github/workflows/build-bsh-tests.yaml
      - usr/bsh/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure
        run: cmake -S usr/bsh/tests -B build -DCMAKE_BUILD_TYPE=Debug
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
