name: Build native libheap

on:
  push:
    paths:
      - .github/workflows/build-libheap-native.yaml
      - lib/heap/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure
        run: cmake -S lib/heap -B build -DCMAKE_BUILD_TYPE=Debug -DHEAP_TESTS=ON
      - name: build
        run: cmake --build build
      - name: test
        run: cmake --build build --target test
