name: CI for BradypOS

on:
  push:
  pull_request:

jobs:
  build-bradypos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-flags:
          - name: "Release"
            build-type: "Release"
          - name: "Debug"
            build-type: "Debug"
          - name: "MinSizeRel"
            build-type: "MinSizeRel"
          - name: "MinSizeRel-LTO"
            build-type: "MinSizeRel"
            extra-flags: "-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON"
    container:
      image: ghcr.io/${{ github.actor }}/builder-arm-none-eabi
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      # See https://github.com/actions/checkout/issues/1014
      options: --user root
    permissions:
      contents: read
      packages: write
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure
        run: cmake -S . -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=arm-gcc.tc -DCMAKE_BUILD_TYPE=${{ matrix.build-flags.build-type }} ${{ matrix.build-flags.extra-flags}} -DCMAKE_INSTALL_PREFIX=$PWD/install
      - name: build
        run: cmake --build build
      - name: install
        run: cmake --build build --target install
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: bradypos-${{ matrix.build-flags.name }}
          path: install/
          if-no-files-found: warn
